---
- hosts: loadbalancers
  become: true

  tasks:
    - name: Ensure hostname set
      hostname: name={{ inventory_hostname }}

  roles:
    - nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted